version: '3.8'


networks:
  inception:

volumes:
  mariadb_volumn:
    driver_opts:
      type: none
      o: bind
      device: /home/tdehne/data/mariadb

  wordpress_volumn:
    driver_opts:
      type: none
      o: bind
      device: /home/tdehne/data/wordpress

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_volumn:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_volumn:/usr/share/nginx/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_volumn:/usr/share/nginx/wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: unless-stopped
